[package]
name = "latex2mmlc"
version = "0.1.0"
authors = ["Hiromu Sugiura <h.sugiura0705@outlook.com>", "Thomas Kehrenberg <tmke8@posteo.net>"]
edition = { workspace = true }
rust-version = { workspace = true }

description   = "Convert LaTeX equations to MathML Core"
repository    = "https://github.com/tmke8/latex2mmlc"
readme        = "README.md"
license       = { workspace = true }
keywords      = ["latex", "mathml"]
categories    = ["science"]

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
strum_macros = "0.26.2"

[dev-dependencies]
insta = { version = "1.38.0", features = ["default"] }
