[package]
name = "latex2mmlc_cli"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
latex2mmlc = { path = "../latex2mmlc" }

clap = { version = "4.3.24", features = ["derive"] }
bumpalo = { workspace = true }
