name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Install Rust toolchain"
        run: rustup show
      - name: "Install cargo insta"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-insta
      - uses: Swatinem/rust-cache@v2
      - name: "Run tests"
        run: cargo insta test --all --all-features --unreferenced reject

  cargo-test-wasm:
    runs-on: ubuntu-latest
    name: "cargo test (wasm)"
    steps:
      - uses: actions/checkout@v4
      - name: "Install Rust toolchain"
        run: rustup target add wasm32-unknown-unknown
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: qmaru/wasm-pack-action@v0.5.0
      - uses: Swatinem/rust-cache@v2
      - name: "Run wasm-pack"
        run: |
          wasm-pack test --node latex2mmlc_wasm
